---
hero_image: images/rate-your-mates.png
theme: turquoise
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Rate Your Mates
description: Use your micro:bit to find out your compatibility with friends!
original_url: https://codeclubprojects.org/en-GB/microbit/rate-your-mates
interests: ''
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps:
- title: Introduction
  completion: engaged
- title: Pressing buttons together
- title: Displaying a rating
- title: Best mates
- title: 'Challenge: Low rating'
- title: Adding an animation
  completion: internal
- title: 'Challenge: More animations'
